schedules:
  linuxbackup:
    disabled: false
    labels:
      myenv: veleronamespace
    annotations:
      myenv: veleronamespace
    schedule: " 32 17 * * * "
    useOwnerReferencesInBackup: true
    template:
      ttl: "240h"
      includedNamespaces:
      - linuxnamespace
      - windowsnamespace
